---
title: "Twitter APIs"
author: "mwk"
date: "2017-10-30"
slug: twitter-apis
categories: ["Twitter"]
tags: ["Twitter data", "Twitter API"]
---

## Twitter data gatekeeping

Twitter data was already trendy, but the *unpresidented* 2016
U.S. election has elevated it to a fever pitch. One of the biggest
drivers of the trend is the widespread, public availability of Twitter
data. Twitter makes much of its user-generated data freely available
to the public via Application Program Interfaces (APIs). APIs refer to
sets of protocols and procedures for interacting with sites. Twitter
maintains several APIs, but in the context of publicly available data
collection two, in particular, stand out.

### 1. Twitter's REST API

Twitter's REST API provides a [set of
protocols](https://developer.twitter.com/en/docs/api-reference-index)
for exploring and interacting with Twitter data related to [statuses
(tweets)](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/intro-to-tweet-json),
[users](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/overview),
and [network connections
(followers/friends)](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference). The
data are RESTful in that they have been archived by
Twitter. Navigating these resting endpoints can, at times, be
[resource
intensive](https://developer.twitter.com/en/docs/basics/things-every-developer-should-know)
and [slow](https://developer.twitter.com/en/docs/basics/rate-limits),
but it also makes it possible to perform [highly complex and specific
queries](https://developer.twitter.com/en/docs/tweets/search/overview/operator_descriptions).

### 2. Twitter's stream API

Twitter data not yet archived and accessible via the REST API can be
accessed using [Twitter's stream API](https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting). As its name suggests, the stream
API provides users with a live stream of Twitter data. Because the
data are streamed, or pushed, to the user, the [stream API reduces
overhead](https://developer.twitter.com/en/docs/basics/things-every-developer-should-know) associated with performing queries on archived data
sources. This makes it possible to collect large amounts of data very
quickly and with relatively little strain on computational
resources. The downside to the stream API is that it is limited to
prospective data collection via
[sampling](https://developer.twitter.com/en/docs/tweets/sample-realtime/overview/GET_statuse_sample)
or [filtering](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview).
